name: CI

on:
  pull_request:
  push:
    branches: [main]
jobs:
  Spelling:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - name: Check Spelling
      run: nix develop --command codespell --ignore-words-list crate,pullrequest,pullrequests .

  Terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Enable magic Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Terraform fmt
        run: nix-shell --run 'terraform fmt -check -recursive ./terraform'
      - name: Terraform init
        run: nix-shell --run 'terraform -chdir=./terraform init'
      - name: Terraform validate
        run: nix-shell --run 'terraform -chdir=./terraform validate -no-color'

  Rust:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main
    - name: Enable magic Nix cache
      uses: DeterminateSystems/magic-nix-cache-action@main
    - name: Check rustfmt
      working-directory: jobset-generator/
      run: nix-shell ../shell.nix --run 'cargo fmt -- --check'
    - name: Check Clippy
      working-directory: jobset-generator/
      run: cargo clippy
    - name: Check tests
      working-directory: jobset-generator/
      run: cargo test


  Nix:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main
    - name: Enable magic Nix cache
      uses: DeterminateSystems/magic-nix-cache-action@main
    - name: Check Formatting
      run: nix develop --command nixpkgs-fmt .

  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main
    - name: Enable magic Nix cache
      uses: DeterminateSystems/magic-nix-cache-action@main
    - name: Check Formatting
      run: nix build -L .#generator.x86_64-linux
